---
- hosts: webservers
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Create gluster volume
      gluster.gluster.gluster_volume:
        state: present
        name: brick1
        bricks: /bricks/brick1/g1
        rebalance: yes
        cluster:
          - 192.168.33.11
          - 192.168.33.12
        run_once: true
    - name: Start gluster services
      service: name=gluster state=restarted enabled=yes
    - name: create gluster data dir
      file:
        path: "{{gluster_data_dir}}"
        state: directory
    - name: Mount gluster 
      shell: mkfs.xfs /dev/sdb1 && mount /dev/sdb1 /gluster/data/
    - name: config nodes
      shell: echo "192.168.33.11 web-1" >> /etc/hosts && echo "192.168.33.12 web-2" >> /etc/hosts
