- hosts: all
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: files/mongo.repo
      dest: /etc/yum.repos.d/
  - name: Install mongodb
    yum:
     name: mongodb-org
     state: present

  - name: Start the service
    service:
      name: mongod
      state: started