CREATE TABLE IF NOT EXISTS public."Books"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" text COLLATE pg_catalog."default" NOT NULL,
    "Author" text COLLATE pg_catalog."default" NOT NULL,
    "Created" text COLLATE pg_catalog."default",
    "Image" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);
