---
- hosts: servers
  become: true
  tasks:
          - name: "Install Epel-Release to install Go"
            yum:
                    name: epel-release
                    state: present
                    
          - name: "Install Go"
            yum:
                    name: golang
                    state: present

          - name: "Install MongoDB Driver"
            shell: "go get go.mongodb.org/mongo-driver/mongo"
