Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.ssh.insert_key = false
    config.vm.network "forwarded_port", guest: 27017, host: 27017
  
    # Run Ansible from the Vagrant Host
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end