---
# These tasks install an set up Gluster
- name: "Format the sdb disk"
  shell: "mkfs.xfs -i size=512 /dev/sdb "
- name: "Create mount point of sdb"
  shell: "mkdir -p /bricks/brick"
- name: "Configure fstab"
  shell: "echo '/dev/sdb /bricks/brick xfs defaults 1 2' >> /etc/fstab"
- name: "Apply changes over fstab"
  shell: "mount -a"
- name: "Ensure changes"
  shell: "mount"
- name: "Install Gluster release" 
  yum:
    name:
      - centos-release-gluster
- name: "Install Gluster server" 
  yum:
    name:
      - glusterfs-server
- name: "Enable Gluster daemon"
  shell: "systemctl enable glusterd"
- name: "Start Gluster daemon"
  shell: "systemctl start glusterd"