version: '3'
services:

  loadbalancer:
    container_name: loadbalancerParcial
    build: ../haproxy
    ports:
      - "8000:80"
      - "1936:1936"
    networks:
      - parcial

  express-gateway-data-store:
    container_name: eg-data-store-parcial
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - libraryapp

  express-gateway:
    container_name: eg-parcial
    image: express-gateway
    ports:
      - "8080:8080"
      - "9876:9876"
    volumes:
      - type: bind
        source: ../appgw
        target: /var/lib/eg
    networks:
      - libraryapp

networks:
  parcial:
    external: true