---
- hosts: db
  become: true
  vars_files:
    - ../glusterfs/vars/main.yml
  vars:
    mysql_root_password: "Password"
  pre_tasks:
    - name: Install DB dependencies
      yum:
        name:
          - epel-release
          - mysql-devel
          - gcc
          - python-devel
          - MySQL-python
          - mariadb-server
    - name: Get Host name
      shell: "echo $HOSTNAME"
      register: hostname
  tasks:
    - import_tasks: ../glusterfs/glusterfs-config.yml
    - import_tasks: ../glusterfs/master-node.yml
    - import_tasks: ../glusterfs/shared-config.yml
    - name: Start MariaDB
      service:
        name: mariadb
        enabled: true
        state: started
    - name: Mysql user confing
      mysql_user:
        login_user: root
        login_password: "{{mysql_root_password}}"
        user: root
        check_implicit_admin: true
        password: "{{mysql_root_password}}"
        host: localhost
    - name: copy file
      copy:
        src: files/p1db.sql
        dest: /tmp/
    - name: Import MariaDB
      mysql_db:
        state: import
        name: icesihealth
        login_password: "{{mysql_root_password}}"
        target: /tmp/p1db.sql

