---
- hosts: webservers
  become: true
  vars_files:
    - vars/main.yml
  vars:
    variable: "print_hostname"
  pre_tasks:
    - name: Ensure epel repository exists
      yum: name=epel-release
  tasks:
    - name: Get Host name
      shell: "echo $HOSTNAME"
      register: print_hostname
    - name: Ensure docroot exists
      file:
        path: "{{nginx_docroot}}"
        state: directory
    - name: Copy html file
      copy: 
        src: files/index.j2
        dest: "{{nginx_docroot}}/index.html"
        mode: 0755
    - name: Run python server
      shell: "(python -m SimpleHTTPServer 8083 >/dev/null 2>&1 &)"
      async: 10
      poll: 0
      args:
        chdir: "{{ nginx_docroot }}"
