# Generated by Django 3.2.7 on 2021-09-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Path', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
            ],
        ),
    ]
