---
- name: Shared GlusterFs Configuration | Create shared folder 
  file:
    path: "{{gluster_share}}"
    state: directory
    mode: '0755'
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['glusterfs'] }}"
- name: Strat Gluster volumen 
  shell: mount.glusterfs "localhost:/{{gluster_name}}" "{{gluster_share}}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['glusterfs'] }}"
